name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
template: |
  ## What’s Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels: "bugfix"

exclude-labels:
  - "skip-changelog"