name: Building Hussar
on: [push]

jobs:
  build_hussar:
    name: Building Hussar components
    runs-on: ubuntu-latest
    steps:
      - name: Checking out codebase
        uses: actions/checkout@v4

      - name: Configuring JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configuring Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Building with Gradle
        run: ./gradlew build

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: |
            hussar-core/build/reports/tests/test
            hussar-applications/**/build/reports/tests/test
            hussar-extensions/**/build/reports/test
            hussar-services/**/build/reports/test