name: Releasing Hussar

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        required: true

jobs:
  release_hussar:
    name: Releasing Hussar components
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checking out codebase
        uses: actions/checkout@v4

      - name: Configuring JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configuring Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configuring Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""

      - name: Releasing with Gradle
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.release-version }}

